language: go
go:
- "1.12.x"
env:
  global:
    GOFLAGS=-mod=vendor
install:
- go get github.com/mitchellh/gox
script:
- make test
- make vet
- make bin VERSION=$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "ud9Gao7CnnTQZ1j8vhUlQ0BeNdrFMUhEhfe6b72OQA7Jqc8xvNYFyzDmdkHU8efWUD4I+pP2vpOwULD7gHgHB+P5pZJVzaNdd+eaMpdtStYn/TjNe3e9NfDm2HEBjWWjxfWQTzMELYTJP7RiKHu+TsrVvMLX1/kkTIAvZ38VfAdyV8r6cvnOqGwWSHUuJLk76pPf54RsFDjwXjD4NS6k2NF8Ic0JgzblUxJD1r6fwRPqB7cp1CALi3YNNy3Ab416TjYF3Si285omvA8pr+G7J8k4M7a6WT7PncpMSKt7UEx1bc4B4doytD38YbDHNCi+kAvojG5/oYeQx+swY6Di6D2z2qiaXGGzwXkFEqd6sL1yuMS+h1bvgxdeqUHnYlM0Gg3kGZqby00+McE4KWpPFYlyMBPvf/TZcbeKd1EXk6SDdLf+C88MJYP1C8vM+vArqfnoK56nAY5jkqIfzwHTCzMnlLmOMgTQ1M/9z9EgT+HI9cm3C+A14TnK/Ca8iDFAYQapUStOaoepFPszJzdKOK/RrpSYjE1ZIw7roKzed8DtZtMY4QMglycs59kSfTw/rCMTNVjWE9gsFLQYUvX0re+85z8t6M7JkJKXICqKWiaMUaPdpcYKcoSeP5ueFiRq9i5iv5xaEf4mq2v9vKSwF1oPSbKUr0C66o04Jl3A8uw="
  file: pkg/terraform-provider-cloudhealth_*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
